services:
  frontend:
    build:
      context: ./coyote-game-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
      - REACT_APP_WS_BASE_URL=ws://localhost:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_ORIGIN=http://localhost:3000
      - DATABASE_URL=sqlite:///sqlite.db